[ERROR] 2020-01-26 17:56:01,181 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: api.justwash.com
Exception in Enqueue Events for Site api.justwash.com
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 87, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 234, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 243, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'192.168.5.241' ([Errno 111] Connection refused)")

[ERROR] 2020-01-26 22:18:12,269 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: api.justwash.com
Exception in Enqueue Events for Site api.justwash.com
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 87, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 234, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 243, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'192.168.5.241' ([Errno 111] Connection refused)")

[ERROR] 2020-01-26 22:20:21,941 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: api.justwash.com
Exception in Enqueue Events for Site api.justwash.com
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 87, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 234, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 243, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 598, in connect
    self._get_server_information()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 975, in _get_server_information
    packet = self._read_packet()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
OperationalError: (2013, 'Lost connection to MySQL server during query')

[DEBUG] 2020-01-27 03:21:53,240 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: api.justwash.com
Queued events for site api.justwash.com
[DEBUG] 2020-01-27 03:22:53,370 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: api.justwash.com
Queued events for site api.justwash.com
